// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	
	int N = Integer.parseInt(args[0]);
	int R = Integer.parseInt(args[0]);
	double Big = 0;
	double Small = 0;
	

	for (int i=0;i<N;i++) {
		double a= (Math.random());
		
		if (a>0.5){Big++;}
		else {Small++;}

	}

	System.out.println("> 0.5:  "+ (int) Big+ " times");
	System.out.println("<= 0.5: "+ (int) Small+ " times");

	if (Small>0){double Ratio= Big/Small;
	System.out.println("Ratio:  "+ Ratio);
	}

	}
}
