// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	
	int N= Integer.parseInt(args[0]);
	int R= Integer.parseInt(args[0]);
	double Big= 0;
	double Small= 0;
	

	while (N>0) {
		double a= (Math.random()+0.5);
		
		if (a>1){Big= Big+1;}
		else {Small= Small+1;}

		N--;

	}

	System.out.println("% java TestRandom "+ R);
	System.out.println("> 0.5:  "+ (int) Big+ " times");
	System.out.println("<= 0.5: "+ (int) Small+ " times");

	if (Small>0){double Ratio= Big/Small;
	System.out.println("Ratio:  "+ Ratio);
	}

	}
}
